apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "finops-operator-exporter-chart.fullname" . }}-repo-envvar-configmap-exporter-md2d926d4b
  labels:
  {{- include "finops-operator-exporter-chart.labels" . | nindent 4 }}
data:
  REPO: {{ .Values.operatorExporterRepoEnvvarConfigmapExporterMd2D926D4B.repo | quote
    }}