apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "finops-operator-exporter-chart.fullname" . }}
  labels:
  {{- include "finops-operator-exporter-chart.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }} 
