apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "finops-operator-exporter.fullname" . }}
  labels:
    {{- include "finops-operator-exporter.labels" . | nindent 4 }}
data:
  REPO: ghcr.io/krateoplatformops
