apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "finops-operator-exporter-chart.fullname" . }}-repo-envvar
  labels:
  {{- include "finops-operator-exporter-chart.labels" . | nindent 4 }}
data:
  REPO: {{ .Values.operatorExporterRepoEnvvarConfigmapExporter.repo | quote
    }}