apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "finops-operator-exporter-chart.fullname" . }}-leader-election
  labels:
  {{- include "finops-operator-exporter-chart.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "finops-operator-exporter-chart.fullname" . }}-leader-election'
subjects:
- kind: ServiceAccount
  name: {{ include "finops-operator-exporter-chart.serviceAccountName" . }}
  namespace: '{{ .Release.Namespace }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "finops-operator-exporter-chart.fullname" . }}-manager
  labels:
  {{- include "finops-operator-exporter-chart.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "finops-operator-exporter-chart.fullname" . }}-manager'
subjects:
- kind: ServiceAccount
  name: {{ include "finops-operator-exporter-chart.serviceAccountName" . }}
  namespace: '{{ .Release.Namespace }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "finops-operator-exporter-chart.fullname" . }}-db-config-getter-rb
  labels:
  {{- include "finops-operator-exporter-chart.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "finops-operator-exporter-chart.fullname" . }} #'{{ include "finops-operator-exporter-chart.fullname" . }}-db-config-getter-role'
subjects:
- kind: ServiceAccount
  name: db-config-getter-sa
  namespace: '{{ .Release.Namespace }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "finops-operator-exporter-chart.fullname" . }}-rb
  labels:
  {{- include "finops-operator-exporter-chart.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "finops-operator-exporter-chart.fullname" . }}-db-config-getter'
subjects:
- kind: ServiceAccount
  name: exporterscraper-config-getter-sa
  namespace: '{{ .Release.Namespace }}'
