apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "finops-operator-exporter-chart.fullname" . }}-controller-manager
  labels:
  {{- include "finops-operator-exporter-chart.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: db-config-getter-sa
  labels:
  {{- include "finops-operator-exporter-chart.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.dbConfigGetterSa.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: exporterscraper-config-getter-sa
  labels:
  {{- include "finops-operator-exporter-chart.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.exporterscraperConfigGetterSa.serviceAccount.annotations | nindent 4 }}