apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: databaseconfigs.finops.krateo.io
spec:
  group: finops.krateo.io
  names:
    kind: DatabaseConfig
    plural: databaseconfigs
    shortNames:
    - dbconf
    singular: databaseconfig
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              clusterName:
                type: string
              host:
                type: string
              notebookPath:
                type: string
              token:
                type: string
            required:
            - host
            - token
            - clusterName
            - notebookPath
            type: object
        type: object
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
